### ISSUE TITLE
How to connect the visdom server in my remote Server using my PC?

### ISSUE THREAD

**Issue by Cheneng** [facebookresearch/visdom#288]
I want to run my code in the remote linux server and observe the training curve in my personal computer.
How to do it? Like to connect the ipython notebook remotely since they are in the same LAN. 
Thanks.

**Comment by JackUrb** [comment]
When running the visdom server on a remote server, you can connect to it by using `<your_remote_server_ip>:<visdom port (default 8097)>` with a web browser

**Comment by Cheneng** [comment]
@JackUrb Oh, Thanks！It's easy.

**Comment by udion** [comment]
I have been trying this for a while but it doesn't work

### on the server I do
`python -m  visdom.server` and I get
![image](https://user-images.githubusercontent.com/18963158/40091962-a7c359da-58f5-11e8-8805-0ed2f866b006.png)

Now my server doesn't have any browser installed so I want to view the output in my local machine

### on local machine I do
* In firefox https://\<ip addr of server>\:8097

and it shows unable to connect.

* I thought that the problem is with the port forwarding. So I manually edited the `~/.ssh/config/ssh_config` file on ***my local machine*** to include `LocalForward 127.0.0.1:8097 127.0.0.1:8097`
* Since it did not work I also tried `RemoteForward 127.0.0.1:8097 127.0.0.1:8097`
* Since it did not work I also tried adding both of them together, i.e 
```
<other stuff about my host>
LocalForward 127.0.0.1:8097 127.0.0.1:8097
RemoteForward 127.0.0.1:8097 127.0.0.1:8097
```
please help, how should i get this thing to work?

**Comment by JackUrb** [comment]
Hi @udion - try connecting over `http` rather than `https`, we haven't configured the visdom server to work over `https`, as most of our users are working on servers without public ips with registered ssl certificates and we haven't had much demand to support `https` yet.

**Comment by rohun-tripathi** [comment]
I am running visdom on the remote server and it times out now. It worked on an earlier instance on a different server.
This happens after I updated to '0.1.8.3'
The error is - ERR_CONNECTION_TIMED_OUT.
This site can’t be reached
<ip addr of server> took too long to respond.

On the terminal, ping <ip addr of server> reports that the remote is up.

**Comment by lvdmaaten** [comment]
@rohun-tripathi Did you try the steps outlined in the FAQ (see below)? Do you see any prints happening in the terminal running your server when you try to connect to it from your browser? Does the problem go away when moving back to an earlier version of visdom?



**Issue: I cannot connect to the visdom server.** First, check that your visdom server is running. You can start the visdom server via python -m visdom.server. Try restarting the server.

If your visdom server is running, but you don't see anything when trying to access visdom in your browser, please check that your network settings don't block traffic between the visdom server and your browser. Traffic may be blocked by a firewall, or you may need to specify a proxy server when starting the visdom server (via the -proxy option). In some cases, it may help to set up an SSH tunnel to your server by adding the following line to your local `~/.ssh/config`: `LocalForward 127.0.0.1:8097 127.0.0.1:8097`

**Comment by JackUrb** [comment]
HI @rohun-tripathi - can you try installing from source and seeing if the issue is still active?

**Comment by ningyanuta** [comment]
I encounter the same issue and solved by "sudo ufw allow 8097". FYI.

**Comment by shirui-japina** [comment]
> When running the visdom server on a remote server, you can connect to it by using `<your_remote_server_ip>:<visdom port (default 8097)>` with a web browser

Gooooooooooooooddd!!!!!!

**Comment by shruthi0898** [comment]
> When running the visdom server on a remote server, you can connect to it by using `<your_remote_server_ip>:<visdom port (default 8097)>` with a web browser

I am still not able to see the results, is there something else that needs to be done?
